package example:pkg;

interface example {
    test1: func() -> future<result<list<string>>>;
    test2: func() -> future<result<list<list<u8>>>>;
    test3: func() -> future<list<list<list<u8>>>>;
}

world example-world {
    export example;
}