package example:pkg;

interface example {
    future1: func() -> future<result<list<string>>>;
    future2: func() -> future<result<list<list<u8>>>>;
    future3: func() -> future<list<list<list<u8>>>>;

    stream1: func() -> stream<result<list<string>>>;
    stream2: func() -> stream<result<list<list<u8>>>>;
    stream3: func() -> stream<list<list<list<u8>>>>;
}

world example-world {
    export example;
}